import Link from "next/link";
import RotatingWord from "@/components/RotatingWord";
import LookGallery from "@/components/LookGallery";
import Reveal from "@/components/Reveal";
import GlowButton from "@/components/GlowButton";
import SiteFooter from "@/components/SiteFooter";
import { issueLabel } from "@/lib/issue";

const CONTENTS = [
  { n: "№01", title: "Add your selfie", page: "or skip — we’ll cast a model" },
  { n: "№02", title: "Pick the vibe", page: "streetwear, old money, Sangeet…" },
  { n: "№03", title: "Post & cop", page: "share the cover, shop the look" },
];

export default function Landing({ isAuthed }: { isAuthed: boolean }) {
  const primaryHref = isAuthed ? "/studio" : "/signup";
  const issue = issueLabel();

  return (
    <main className="min-h-screen bg-paper text-ink">
      <div className="mx-auto max-w-6xl edge-rules">
        {/* Masthead strip */}
        <header className="sticky top-0 z-40 bg-paper/85 backdrop-blur-sm">
          <div className="flex items-center justify-between px-5 py-3.5 sm:px-8">
            <Link href="/" className="font-display text-2xl font-semibold tracking-tight">
              Looksy
            </Link>
            <div className="flex items-center gap-5">
              <span className="hidden font-mono text-[11px] uppercase tracking-[0.2em] text-vermilion sm:inline">
                The Issue {issue} · ₹Free
              </span>
              {isAuthed ? (
                <Link href="/studio" className="text-sm text-ink-60 transition hover:text-vermilion">
                  Open Studio →
                </Link>
              ) : (
                <nav className="flex items-center gap-5 text-sm">
                  <Link href="/login" className="text-ink-60 transition hover:text-vermilion">
                    Log in
                  </Link>
                  <Link
                    href="/signup"
                    className="bg-vermilion px-3.5 py-2 text-xs font-medium uppercase tracking-wide text-paper transition hover:bg-vermilion-ink"
                  >
                    Subscribe
                  </Link>
                </nav>
              )}
            </div>
          </div>
          <div className="h-px w-full bg-ink/15" />
        </header>

        {/* Cover */}
        <section className="relative isolate grid grid-cols-1 gap-8 overflow-hidden px-5 pb-16 pt-10 sm:px-8 lg:grid-cols-12 lg:gap-6 lg:pb-24 lg:pt-16">
          <span
            aria-hidden
            className="ghost-masthead pointer-events-none absolute left-1/2 top-[34%] z-0 -translate-x-1/2 -translate-y-1/2 select-none whitespace-nowrap font-display text-[24vw] font-semibold leading-none tracking-tighter"
          >
            LOOKSY
          </span>
          <div className="relative z-10 lg:col-span-7">
            <p className="kicker mb-6">An AI fashion weekly · Shot in India</p>
            <h1 className="font-display font-medium leading-[0.92] tracking-tight text-[clamp(3rem,10vw,7.5rem)]">
              <span className="block">Try on</span>
              <RotatingWord />
            </h1>
            <p className="mt-7 max-w-md font-serif text-lg leading-relaxed text-ink-60">
              Upload a selfie. Pick a vibe. Get a cover so good it’s basically a
              personality — and every piece is instantly shoppable. Free.
            </p>
            <div className="mt-9 flex items-center gap-6">
              <GlowButton href={primaryHref}>
                {isAuthed ? "Open this issue" : "Open this issue"} →
              </GlowButton>
              {!isAuthed && (
                <Link
                  href="/login"
                  className="text-sm text-ink-60 underline-offset-4 transition hover:text-vermilion hover:underline"
                >
                  Already a subscriber?
                </Link>
              )}
            </div>
          </div>

          {/* The one full cover — the only colour on the page */}
          <div className="relative z-10 lg:col-span-5">
            <div className="relative border border-ink/15 bg-paper-2 p-2">
              <div className="absolute left-4 top-4 z-10 flex items-center gap-2">
                <span className="bg-paper/85 px-2 py-0.5 font-display text-xs tracking-tight">
                  LOOKSY
                </span>
                <span className="bg-paper/85 px-2 py-0.5 font-mono text-[10px] uppercase tracking-[0.15em] text-vermilion">
                  {issue}
                </span>
              </div>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src="/examples/festive.jpg"
                alt="This week’s cover, generated by Looksy"
                className="aspect-[3/4] w-full object-cover"
              />
              <p className="mt-2 px-1 font-serif text-sm italic text-ink-60">
                The Cover — styled in three taps.
              </p>
            </div>
          </div>
        </section>

        <div className="h-px w-full bg-ink/15" />

        {/* Contents */}
        <section className="px-5 py-14 sm:px-8">
          <p className="kicker mb-6">Contents</p>
          <ul>
            {CONTENTS.map((c) => (
              <li
                key={c.n}
                className="flex items-baseline border-b border-ink/10 py-4 last:border-0"
              >
                <span className="w-16 shrink-0 font-mono text-sm text-vermilion">{c.n}</span>
                <span className="font-display text-xl tracking-tight sm:text-2xl">
                  {c.title}
                </span>
                <span className="leader" />
                <span className="shrink-0 font-serif text-sm italic text-ink-60">
                  {c.page}
                </span>
              </li>
            ))}
          </ul>
        </section>

        <div className="h-px w-full bg-ink/15" />

        {/* This week's covers */}
        <section className="px-5 py-16 sm:px-8">
          <Reveal>
            <div className="mb-8 flex items-end justify-between">
              <div>
                <p className="kicker mb-2">The Gallery</p>
                <h2 className="font-display text-3xl font-medium tracking-tight sm:text-4xl">
                  This week’s covers
                </h2>
              </div>
              <p className="hidden font-mono text-[11px] uppercase tracking-[0.18em] text-ink-30 sm:block">
                Every piece shoppable
              </p>
            </div>
          </Reveal>
          <Reveal delay={120}>
            <LookGallery />
          </Reveal>
          <p className="mt-8 text-center font-mono text-xs uppercase tracking-[0.18em] text-ink-30">
            1,20,000+ covers shot this week
          </p>
        </section>

        <div className="h-px w-full bg-ink/15" />

        {/* Closing cover line */}
        <section className="px-5 py-20 text-center sm:px-8">
          <Reveal>
            <h2 className="mx-auto max-w-2xl text-balance font-display text-4xl font-medium leading-[1.02] tracking-tight sm:text-6xl">
              Your next cover is{" "}
              <span className="italic text-vermilion">one selfie</span> away.
            </h2>
            <div className="mt-10 flex justify-center">
              <GlowButton href={primaryHref}>
                {isAuthed ? "Open Studio" : "Shoot your first cover"} →
              </GlowButton>
            </div>
          </Reveal>
        </section>

        {/* Colophon */}
        <SiteFooter />
      </div>
    </main>
  );
}
