import TiltCard from "@/components/TiltCard";

const GALLERY = [
  { id: "streetwear", label: "Streetwear", price: "₹2,449" },
  { id: "oldmoney", label: "Old Money", price: "₹6,990" },
  { id: "party", label: "Party Wear", price: "₹3,499" },
  { id: "festive", label: "Festive", price: "₹4,250" },
  { id: "techwear", label: "Techwear", price: "₹2,899" },
  { id: "casual", label: "Everyday", price: "₹1,299" },
];

/** A grid of real, AI-generated example looks — this week's plates, shoppable. */
export default function LookGallery() {
  return (
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 sm:gap-4">
      {GALLERY.map((g) => (
        <TiltCard
          key={g.id}
          className="group border border-ink/12 bg-paper-2 p-2"
        >
          <div className="relative overflow-hidden">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={`/examples/${g.id}.jpg`}
              alt={`${g.label} look generated by Looksy`}
              loading="lazy"
              className="aspect-[3/4] w-full object-cover transition duration-500 group-hover:scale-[1.04]"
            />
          </div>
          <div className="mt-2 flex items-baseline justify-between gap-2 border-t border-ink/10 pt-2">
            <span className="text-[12px] text-ink">{g.label}</span>
            <span className="font-mono text-[11px] text-ink-60">
              {g.price} &rarr;
            </span>
          </div>
        </TiltCard>
      ))}
    </div>
  );
}
