import TiltCard from "@/components/TiltCard";

const GALLERY = [
  { id: "streetwear", label: "Streetwear", price: "₹2,449" },
  { id: "oldmoney", label: "Old Money", price: "₹6,990" },
  { id: "party", label: "Party Wear", price: "₹3,499" },
  { id: "festive", label: "Festive", price: "₹4,250" },
  { id: "techwear", label: "Techwear", price: "₹2,899" },
  { id: "casual", label: "Everyday", price: "₹1,299" },
];

/** A grid of real, AI-generated example looks — tilt on hover, shoppable feel. */
export default function LookGallery() {
  return (
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 sm:gap-4">
      {GALLERY.map((g) => (
        <TiltCard
          key={g.id}
          className="group relative overflow-hidden rounded-2xl bg-[#101015] p-2 shadow-[0_30px_60px_-20px_rgba(0,0,0,0.8)] ring-1 ring-white/[0.06]"
        >
          <div className="relative overflow-hidden rounded-xl ring-1 ring-white/[0.08]">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={`/examples/${g.id}.jpg`}
              alt={`${g.label} look generated by Looksy`}
              loading="lazy"
              className="aspect-[3/4] w-full object-cover transition duration-500 group-hover:scale-[1.04]"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/75 via-transparent to-transparent" />
            <div className="absolute inset-x-0 bottom-0 flex items-end justify-between gap-2 p-3">
              <span className="text-[11px] uppercase tracking-[0.15em] text-champagne drop-shadow">
                {g.label}
              </span>
              <span className="text-[11px] text-white/75">{g.price} · Shop ↗</span>
            </div>
          </div>
        </TiltCard>
      ))}
    </div>
  );
}
